# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CLPracticeProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CLPracticeProject
  pod 'RxCocoa'
  pod 'Moya-ModelMapper/RxSwift'
  pod 'RxOptional'
  pod 'PromisesSwift'

  target 'CLPracticeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CLPracticeProjectUITests' do
    # Pods for testing
  end

end
